spring.application.name=nextgen
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.acks=all
#spring.kafka.producer.retries=3
#spring.kafka.producer.properties.enable.idempotence=true



#CONSUMER
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeSerializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeSerializer


